persistence:
  datadir: /Users/cogniveon/src/camtes/dtpoc/data
  nodeAffinity:
    key: kubernetes.io/hostname
    operator: In
    values:
      - "docker-desktop"

orchestrator:
  operator:
    image: ghcr.io/cam-digital-hospitals/orchestrator-operator
    version: latest
  api:
    image: ghcr.io/cam-digital-hospitals/orchestrator-api
    version: latest
  ui:
    image: nginx
    version: latest


ingress-nginx:
  controller:
    replicaCount: 1
#     service:
#       externalTrafficPolicy: Local
#     config:
#       use-proxy-protocol: "true"
#     hostPort:
#       # -- Enable 'hostPort' or not
#       enabled: true