apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: analytics.eng.cam.ac.uk
spec:
  group: eng.cam.ac.uk
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                description:
                  type: string
                jobType:
                  type: string
                  enum:
                    - persistent
                    - scheduled
                    - ondemand
                port:
                  type: integer
                  minimum: 1
                  maximum: 65535
                  description: "Port to map external traffic (Optional: if analytics module has a server)"
                reps:
                  type: integer
                  minimum: 1
                  maximum: 100
                  description: "Number of job run required to be completed (V1JobSpec.completions)"
                schedule:
                  type: string
                  description: "Cron schedule expression for scheduled jobType"
                env:
                  type: object
                  additionalProperties:
                    type: string
                  description: "Environment variables for job runs"
              required:
                - image
                - jobType
              oneOf:
                - properties:
                    jobType:
                      enum:
                        - persistent
                  not:
                    required:
                      - reps
                - properties:
                    jobType:
                      enum:
                        - scheduled
                  required:
                    - reps
                    - schedule
                - properties:
                    jobType:
                      enum:
                        - ondemand
                  required:
                    - reps
                  not:
                    required:
                      - port
                      - schedule
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Type
          type: string
          description: "The type of job"
          jsonPath: .spec.jobType
        - name: Image
          type: string
          description: "The container image"
          jsonPath: .spec.image
  scope: Namespaced
  names:
    plural: analytics
    singular: analytic
    kind: Analytics
    shortNames:
      - ana