apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-ui
  labels:
    app: orchestrator-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator-ui
  template:
    metadata:
      labels:
        app: orchestrator-ui
    spec:
      containers:
        - name: ui
          image: {{ .Values.orchestrator.ui.image }}:{{ .Values.orchestrator.ui.version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80