apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orchestrator-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
spec:
  ingressClassName: nginx
  rules:
  - host: jolly-crucial-stork.ngrok-free.app
    http:
      paths:
      - path: /api/orchestrator
        pathType: Prefix
        backend:
          service:
            name: orchestrator-api-svc
            port:
              number: 80