apiVersion: v1
kind: ConfigMap
metadata:
  name: nodered-flow
  namespace: {{ .Release.Namespace }}
data:
  flow.json: |
    [
      {
        "id": "flow1",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": ""
      },
      {
        "id": "inject1",
        "type": "inject",
        "z": "flow1",
        "name": "",
        "props": [
          {
            "p": "payload"
          },
          {
            "p": "topic",
            "vt": "str"
          }
        ],
        "repeat": "",
        "crontab": "",
        "once": true,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "Hello, World!",
        "payloadType": "str",
        "x": 200,
        "y": 100,
        "wires": [
          [
            "debug1"
          ]
        ]
      },
      {
        "id": "debug1",
        "type": "debug",
        "z": "flow1",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "targetType": "none",
        "statusVal": "",
        "statusType": "auto",
        "x": 400,
        "y": 100,
        "wires": []
      }
    ]