apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
    spec:
      containers:
        - name: nodered
          image: nodered/node-red:latest
          ports:
            - containerPort: 1880
          volumeMounts:
            - name: nodered-flow
              mountPath: /data/flows.json
              subPath: flow.json
      volumes:
        - name: nodered-flow
          configMap:
            name: nodered-flow