apiVersion: v1
kind: PersistentVolume
metadata:
  name: orchestrator-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: {{ .Values.persistence.dataRoot }}/orchestrator_data/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: {{ .Values.persistence.nodeAffinity.key }}
              operator: {{ .Values.persistence.nodeAffinity.operator }}
              values: {{ toYaml .Values.persistence.nodeAffinity.values | nindent 14 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orchestrator-pvc
  namespace: {{ .Release.Namespace }}
spec:
  volumeName: orchestrator-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi